/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: database.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "database.pb-c.h"
void   database__request__init
                     (Database__Request         *message)
{
  static const Database__Request init_value = DATABASE__REQUEST__INIT;
  *message = init_value;
}
size_t database__request__get_packed_size
                     (const Database__Request *message)
{
  assert(message->base.descriptor == &database__request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t database__request__pack
                     (const Database__Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &database__request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t database__request__pack_to_buffer
                     (const Database__Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &database__request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Database__Request *
       database__request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Database__Request *)
     protobuf_c_message_unpack (&database__request__descriptor,
                                allocator, len, data);
}
void   database__request__free_unpacked
                     (Database__Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &database__request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   database__response__init
                     (Database__Response         *message)
{
  static const Database__Response init_value = DATABASE__RESPONSE__INIT;
  *message = init_value;
}
size_t database__response__get_packed_size
                     (const Database__Response *message)
{
  assert(message->base.descriptor == &database__response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t database__response__pack
                     (const Database__Response *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &database__response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t database__response__pack_to_buffer
                     (const Database__Response *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &database__response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Database__Response *
       database__response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Database__Response *)
     protobuf_c_message_unpack (&database__response__descriptor,
                                allocator, len, data);
}
void   database__response__free_unpacked
                     (Database__Response *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &database__response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor database__request__field_descriptors[1] =
{
  {
    "query",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Database__Request, query),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned database__request__field_indices_by_name[] = {
  0,   /* field[0] = query */
};
static const ProtobufCIntRange database__request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor database__request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "database.Request",
  "Request",
  "Database__Request",
  "database",
  sizeof(Database__Request),
  1,
  database__request__field_descriptors,
  database__request__field_indices_by_name,
  1,  database__request__number_ranges,
  (ProtobufCMessageInit) database__request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor database__response__field_descriptors[2] =
{
  {
    "message",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Database__Response, message),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "success",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Database__Response, success),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned database__response__field_indices_by_name[] = {
  0,   /* field[0] = message */
  1,   /* field[1] = success */
};
static const ProtobufCIntRange database__response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor database__response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "database.Response",
  "Response",
  "Database__Response",
  "database",
  sizeof(Database__Response),
  2,
  database__response__field_descriptors,
  database__response__field_indices_by_name,
  1,  database__response__number_ranges,
  (ProtobufCMessageInit) database__response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
